version: '3.8'

services:
  app:
    build:
      context: .
      target: backend
    container_name: SA_BE
    ports:
      - "8000:8000"
    volumes:
      - ./docker/env/.env.prod:/var/www/.env
    depends_on:
      - pgsql

  socket:
    build:
      context: .
      target: socket
    container_name: SA_SOCKET
    ports:
      - "3000:3000"

  pgsql:
    image: postgres:latest
    container_name: SA_DB
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata:
